gargantuan_monsters = {
    "Leviathan",
    "Ancient Copper Dragon",
    "Roc",
    "Phoenix",
    "Ancient Silver Dragon",
    "Kraken",
    "Ancient White Dragon",
    "Ancient Bronze Dragon",
    "Astral Dreadnought",
    "Purple Worm",
    "Tarrasque",
    "Brontosaurus",
    "Zaratan",
    "Dragon Turtle",
    "Ancient Brass Dragon",
    "Ancient Red Dragon",
    "Elder Tempest",
    "Ancient Gold Dragon",
    "Ancient Blue Dragon",
    "Ancient Green Dragon",
    "Ancient Black Dragon",
    "Neothelid"
    "Joji"
}

huge_monsters = {
    "Mouth of Grolantor",
    "Adult Silver Dragon",
    "Giant Constrictor Snake",
    "Sibriex",
    "Hill Giant",
    "Stegosaurus",
    "Nightwalker",
    "Adult Bronze Dragon",
    "Stone Giant",
    "Awakened Tree",
    "Adult Black Dragon",
    "Tyrannosaurus Rex",
    "Adult White Dragon",
    "Adult Blue Dracolich",
    "Elder Oblex",
    "Ki-rin",
    "Balor",
    "Adult Green Dragon",
    "Mammoth",
    "Empyrean",
    "Treant",
    "Giant Shark",
    "Giant Ape",
    "Fire Giant",
    "Storm Giant Quintessent",
    "Frost Giant Everlasting One",
    "Goristro",
    "Yuan-ti Anathema",
    "Remorhaz",
    "Hydra",
    "Froghemoth",
    "Cloud Giant Smiling One",
    "Killer Whale",
    "Ankylosaurus",
    "Molydeus",
    "Adult Brass Dragon",
    "Cyclops",
    "Fomorian",
    "Triceratops",
    "Storm Giant",
    "Fire Giant Dreadnought",
    "Giant Elk",
    "Adult Blue Dragon",
    "Adult Gold Dragon",
    "Hellfire Engine",
    "Quetzalcoatlus",
    "Frost Giant",
    "Stone Giant Dreamwalker",
    "Abominable Yeti",
    "Adult Copper Dragon",
    "Giant Crocodile",
    "Adult Red Dragon",
    "Cloud Giant",
    "Dire Troll",
    "Elephant",
    "Frost Salamander",
    "Behir"
}

large_monsters = {
    "Winter Wolf",
    "Cadaver Collector",
    "Otyugh",
    "Giant Scorpion",
    "Young Remorhaz",
    "Displacer Beast",
    "Hunter Shark",
    "Wastrilith",
    "Lion",
    "Shoosuva",
    "Death Tyrant",
    "Rug of Smothering",
    "Tlincalli",
    "Merrow",
    "Dao",
    "Beholder Zombie",
    "Ettin",
    "Griffon",
    "Glabrezu",
    "Gynosphinx",
    "Venom Troll",
    "Myconid Sovereign",
    "Armanite",
    "Elk",
    "Young Red Shadow Dragon",
    "Yuan-ti Abomination",
    "Pegasus",
    "Chuul",
    "Giant Sea Horse",
    "Death Kiss",
    "Retriever",
    "Blue Slaad",
    "Barlgura",
    "Giant Toad",
    "Marut",
    "Stench Kow",
    "Young Green Dragon",
    "Mindwitness",
    "Rot Troll",
    "Allosaurus",
    "Gas Spore",
    "Giant Spider",
    "Giant Bat",
    "Marilith",
    "Death Tyrant (in lair)",
    "Nightmare",
    "Shambling Mound",
    "Giant Goat",
    "Barghest",
    "Efreeti",
    "Saber-toothed Tiger",
    "Polar Bear",
    "Ox",
    "Kruthik Hive Lord",
    "Young Red Dragon",
    "Crocodile",
    "Nalfeshnee",
    "Giant Strider",
    "Ogre Zombie",
    "Dire Wolf",
    "Djinni",
    "Spirit Troll",
    "Sahuagin Baron",
    "Camel",
    "Female Steeder",
    "Giant Eagle",
    "Axe Beak",
    "Steel Predator",
    "Guardian Naga",
    "Catoblepas",
    "Flail Snail",
    "Air Elemental",
    "Corpse Flower",
    "Pentadrone",
    "Warhorse",
    "Owlbear",
    "Pit Fiend",
    "Earth Elemental",
    "Trapper",
    "Manticore",
    "Young Brass Dragon",
    "Young Blue Dragon",
    "Balhannoth",
    "Ogre Battering Ram",
    "Tiger",
    "Troll",
    "Yeth Hound",
    "Iron Golem",
    "Young Gold Dragon",
    "Banderhobb",
    "Young Black Dragon",
    "Minotaur Skeleton",
    "Ochre Jelly",
    "Plesiosaurus",
    "Howler",
    "Stone Golem",
    "Fire Elemental",
    "Worg",
    "Water Weird",
    "Star Spawn Hulk",
    "Ice Devil",
    "Centaur",
    "Young White Dragon",
    "Planetar",
    "Carrion Crawler",
    "Hippogriff",
    "Rhinoceros",
    "Young Bronze Dragon",
    "Warhorse Skeleton",
    "Hook Horror",
    "Draft Horse",
    "Androsphinx",
    "Salamander",
    "Boneclaw",
    "Chasme",
    "Chimera",
    "Giant Hyena",
    "Bone Naga",
    "Ogre Chain Brute",
    "Lamia",
    "Ogre",
    "Giant Octopus",
    "Horned Devil",
    "Yeti",
    "Cow",
    "Minotaur",
    "Phase Spider",
    "Solar",
    "Draegloth",
    "Oni",
    "Water Elemental",
    "Vrock",
    "Marid",
    "Gray Render",
    "Bone Devil",
    "Aurochs",
    "Ankheg",
    "Wyvern",
    "Annis Hag",
    "Aboleth",
    "Riding Horse",
    "Hezrou",
    "Yagnoloth",
    "Cave Bear",
    "Gelatinous Cube",
    "Constrictor Snake",
    "Red Slaad",
    "Devourer",
    "Bulette",
    "Elder Brain",
    "Black Pudding",
    "Girallon",
    "Unicorn",
    "Spirit Naga",
    "Beholder",
    "Umber Hulk",
    "Roper",
    "Ogre Howdah",
    "Nycaloth",
    "Beholder (in lair)",
    "Ulitharid",
    "Young Silver Dragon",
    "Hadrosaurus",
    "Young Copper Dragon",
    "Shield Guardian",
    "Half-ogre",
    "Giant Lizard",
    "Drider",
    "Ogre Bolt Launcher",
    "Leucrotta",
    "Grick Alpha",
    "Giant Owl",
    "Giant Vulture",
    "Clay Golem",
    "Green Slaad",
    "Rothe",
    "Orthon",
    "Cloaker",
    "Giant Boar",
    "Gorgon",
    "Brown Bear"
}

medium_monsters = {
    "Hell Hound",
    "Basilisk",
    "Brass Dragon Wyrmling",
    "Swarm of Rot Grubs",
    "Green Abishai",
    "Wereboar",
    "Firenewt Warlock of Imix",
    "Drow Matron Mother",
    "Blink Dog",
    "Duergar Despot",
    "Specter",
    "Wolf",
    "Oaken Bolter",
    "Lost Sorrowsworn",
    "Drow Favored Consort",
    "Hydroloth",
    "Hobgoblin Iron Shadow",
    "Violet Fungus",
    "Winter Eladrin",
    "Satyr",
    "Chain Devil",
    "Cave Fisher",
    "Death Knight",
    "Drow Mage",
    "Drow Priestess of Lolth",
    "Gauth",
    "Drow Elite Warrior",
    "Swarm of Bats",
    "Rakshasa",
    "Orc War Chief",
    "Lonely Sorrowsworn",
    "Gnoll Flesh Gnawer",
    "Dimetrodon",
    "Soul Monger",
    "Green Dragon Wyrmling",
    "Wood Woad",
    "Panther",
    "Banshee",
    "Yochlol",
    "Spawn of Kyuss",
    "Orc Nurtured One of Yurtrus",
    "Animated Armor",
    "Githyanki Supreme Commander",
    "Galeb Duhr",
    "Thorny",
    "Star Spawn Seer",
    "Shrieker",
    "Mind Flayer Lich",
    "Invisible Stalker",
    "Swarm of Poisonous Snakes",
    "Sahuagin",
    "Mind Flayer Arcanist",
    "Bodak",
    "Fire Snake",
    "Bronze Dragon Wyrmling",
    "Deer",
    "Nagpa",
    "Gnoll Hunter",
    "Quaggoth Spore Servant",
    "Lemure",
    "Adult Kruthik",
    "Darkling Elder",
    "Mule",
    "Hobgoblin",
    "Morkoth (in lair)",
    "Deva",
    "Needle Blight",
    "Ghost",
    "Sword Wraith Commander",
    "Dybbuk",
    "Duergar",
    "Shadow Dancer",
    "Thri-kreen",
    "Duergar Screamer",
    "Merfolk",
    "Sea Spawn",
    "Shadow",
    "Giant Weasel",
    "Kuo-toa Archpriest",
    "Bheur Hag",
    "Guard Drake",
    "Stone Defender",
    "Duergar Stone Guard",
    "Kuo-toa Whip",
    "Ettercap",
    "Summer Eladrin",
    "Abyssal Wretch",
    "Orc Red Fang of Shargaas",
    "Lizardfolk",
    "Quaggoth Thonot",
    "Deathlock",
    "Lich",
    "Babau",
    "Mimic",
    "Eidolon",
    "Skeleton",
    "White Abishai",
    "Mastiff",
    "Githyanki Knight",
    "Slithering Tracker",
    "Grell",
    "Ghast",
    "Harpy",
    "Githzerai Enlightened",
    "Tridrone",
    "Hyena",
    "Orc Claw of Luthic",
    "Wererat",
    "Nupperibo",
    "Spectator",
    "Gnoll Fang of Yeenoghu",
    "Pteranodon",
    "Red Abishai",
    "Blue Abishai",
    "Alhoon",
    "Specter (poltergeist)",
    "Star Spawn Mangler",
    "Deep Rothe",
    "Githyanki Warrior",
    "Lizardfolk Shaman",
    "Yuan-ti Malison",
    "Orc Hand of Yurtrus",
    "Skull Lord",
    "Grick",
    "Hungry Sorrowsworn",
    "Hobgoblin Warlord",
    "Flesh Golem",
    "Stone Cursed",
    "Earth Elemental Myrmidon",
    "Revenant",
    "Reef Shark",
    "Githyanki Gish",
    "Drow",
    "Hobgoblin Captain",
    "Gray Ooze",
    "Sahuagin Priestess",
    "Tanarukk",
    "Tortle",
    "Giant Wolf Spider",
    "Black Abishai",
    "Deathlock Mastermind",
    "Shadow Demon",
    "Morkoth",
    "Copper Dragon Wyrmling",
    "Drow Arachnomancer",
    "Maw Demon",
    "Vulture",
    "Medusa",
    "Shadow Mastiff",
    "Vampire (warrior)",
    "Fire Elemental Myrmidon",
    "Alkilith",
    "Swarm of Rats",
    "Maurezhi",
    "Giant Badger",
    "Yuan-ti Pureblood",
    "Swarm of Ravens",
    "Deep Scion",
    "Couatl",
    "Piercer",
    "Incubus",
    "Yuan-ti Pit Master",
    "Bugbear Chief",
    "Green Hag",
    "Death Dog",
    "Drow House Captain",
    "Air Elemental Myrmidon",
    "Orc",
    "Gnoll Witherling",
    "Arcanaloth",
    "Deinonychus",
    "Gargoyle",
    "Water Elemental Myrmidon",
    "Nothic",
    "Helmed Horror",
    "Githyanki Kith'rak",
    "Blue Dragon Wyrmling",
    "Vampiric Mist",
    "Bulezau",
    "Neogi Master",
    "Death Slaad",
    "Yuan-ti Nightmare Speaker",
    "Canoloth",
    "Yuan-ti Mind Whisperer",
    "Sea Hag",
    "Spring Eladrin",
    "Azer",
    "Kuo-toa",
    "Night Hag",
    "Drow Shadowblade",
    "Pony",
    "Boar",
    "Drow Inquisitor",
    "Bullywug",
    "Gray Slaad",
    "Githzerai Anarch",
    "Sword Wraith Warrior",
    "Vampire Spawn",
    "Skulk",
    "Gloom Weaver",
    "Goat",
    "Choldrith",
    "Xorn",
    "Dolphin",
    "Nabassu",
    "Duergar Warlord",
    "Giant Frog",
    "Angry Sorrowsworn",
    "Swarm of Insects",
    "Red Dragon Wyrmling",
    "Dryad",
    "Duergar Soulblade",
    "Ape",
    "Peryton",
    "Jackalwere",
    "Amnizu",
    "Firenewt Warrior",
    "Ghoul",
    "Mezzoloth",
    "Oinoloth",
    "Star Spawn Larva Mage",
    "Silver Dragon Wyrmling",
    "Mummy Lord",
    "Quaggoth",
    "Duodrone",
    "Giant Wasp",
    "Iron Cobra",
    "Zombie",
    "Aarakocra",
    "Rust Monster",
    "Half-Red Dragon Veteran",
    "Gnoll",
    "Black Bear",
    "Duergar Mind Master",
    "Vine Blight",
    "Orc Eye of Gruumsh",
    "Giant Crab",
    "Yuan-ti Broodguard",
    "Vampire",
    "Male Steeder",
    "Adult Oblex",
    "Werebear",
    "Duergar Xarrorn",
    "Orog",
    "Lich (in lair)",
    "Erinyes",
    "Mind Flayer",
    "Cambion",
    "Troglodyte",
    "Kenku",
    "Myconid Adult",
    "Wraith",
    "Mummy Lord (in lair)",
    "Bronze Scout",
    "Gibbering Mouther",
    "Rutterkin",
    "Grimlock",
    "Black Dragon Wyrmling",
    "Wight",
    "Githzerai Zerth",
    "Swarm of Quippers",
    "Weretiger",
    "Deathlock Wight",
    "Mummy",
    "Githzerai Monk",
    "Lizard King/Queen",
    "Orc Blade of Ilneval",
    "Allip",
    "Giant Poisonous Snake",
    "Duergar Kavalrachni",
    "Barbed Devil",
    "Merrenoloth",
    "Dhergoloth",
    "Bugbear",
    "Gold Dragon Wyrmling",
    "Succubus",
    "White Dragon Wyrmling",
    "Tortle Druid",
    "Meazel",
    "Hobgoblin Devastator",
    "Autumn Eladrin",
    "Giff",
    "Swarm of Cranium Rats",
    "Werewolf",
    "Scarecrow",
    "Flind",
    "Merregon",
    "Vampire (spellcaster)",
    "Bearded Devil",
    "Narzugon",
    "Duergar Hammerer",
    "Ultroloth",
    "Monodrone",
    "Quadrone",
    "Gnoll Pack Lord",
    "Berbalang",
    "Doppelganger"
}

small_monsters = {
    "Grung",
    "Manes",
    "Derro",
    "Myconid Sprout",
    "Ice Mephit",
    "Goblin Boss",
    "Baboon",
    "Giant Fire Beetle",
    "Awakened Shrub",
    "Kobold Dragonshield",
    "Octopus",
    "Korred",
    "Derro Savant",
    "Goblin",
    "Darkmantle",
    "Dretch",
    "Kobold Inventor",
    "Blood Hawk",
    "Wretched Sorrowsworn",
    "Winged Kobold",
    "Boggle",
    "Kobold Scale Sorcerer",
    "Smoke Mephit",
    "Neogi",
    "Meenlock",
    "Giant Rat",
    "Redcap",
    "Steam Mephit",
    "Star Spawn Grue",
    "Grung Elite Warrior",
    "Magma Mephit",
    "Young Kruthik",
    "Kobold",
    "Grung Wildling",
    "Magmin",
    "Mud Mephit",
    "Flying Sword",
    "Jackal",
    "Nilbog",
    "Eagle",
    "Darkling",
    "Choker",
    "Chitine",
    "Vegepygmy",
    "Spined Devil",
    "Xvart",
    "Flumph",
    "Xvart Warlock of Raxivort",
    "Twig Blight",
    "Vegepygmy Chief",
    "Dust Mephit",
    "Svirfneblin",
    "Giant Centipede",
    "Cockatrice"
}

tiny_monsters = {
    "Cat",
    "Intellect Devourer",
    "Young Faerie Dragon",
    "Pixie",
    "Imp",
    "Vargouille",
    "Weasel",
    "Adult Faerie Dragon",
    "Raven",
    "Gazer",
    "Quasit",
    "Crab",
    "Bat",
    "Sprite",
    "Badger",
    "Crawling Claw",
    "Demilich",
    "Oblex Spawn",
    "Neogi Hatchling",
    "Frog",
    "Lizard",
    "Cranium Rat",
    "Will-o-wisp",
    "Demilich (in lair)",
    "Pseudodragon",
    "Homunculus",
    "Quipper",
    "Sea Horse",
    "Spider",
    "Velociraptor",
    "Flying Snake",
    "Scorpion",
    "Rat",
    "Poisonous Snake",
    "Flameskull",
    "Quickling",
    "Hawk",
    "Stirge",
    "Owl",
    "Slaad Tadpole"
}
